import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import type {
  CorridorId,
  Dock,
  DockAccess,
  DockFlag,
  Ethanol,
  FuelQuote,
  Product,
  RegionId,
  StateCode,
} from "../src/lib/types";

type Addition = {
  id: string;
  name: string;
  region: RegionId;
  city: string;
  state: StateCode;
  lat: number;
  lng: number;
  phone: string | null;
  website: string | null;
  hours?: string | null;
  notes: string;
  access?: DockAccess;
  ethanol?: Ethanol;
  products?: Product[];
  sourceUrl?: string | null;
};

const HOME_REGION: Record<string, RegionId> = {
  "galveston-bay": "texas",
  "upper-keys": "keys",
};

function callQuotes(products: Product[]): FuelQuote[] {
  return products.map((product) => ({
    product,
    pricePerGallon: null,
    ethanol: product === "diesel" ? "unknown" : "unknown",
    status: "call" as const,
    taxIncluded: null,
  }));
}

function toDock(row: Addition): Dock {
  return {
    id: row.id,
    name: row.name,
    corridor: null,
    region: row.region,
    city: row.city,
    state: row.state,
    lat: row.lat,
    lng: row.lng,
    phone: row.phone,
    hours: row.hours ?? null,
    website: row.website,
    notes: row.notes,
    access: row.access ?? "public",
    ethanol: row.ethanol ?? "unknown",
    quotes: callQuotes(row.products ?? ["87", "diesel"]),
    lastVerifiedAt: null,
    lastVerifiedSource: row.website ? "marina site" : null,
    sourceUrl: row.sourceUrl ?? row.website,
  };
}

const DROP_IDS = new Set(["kemah-boardwalk-marina", "watergate-yachting-center"]);

const HOME_PATCHES: Record<
  string,
  Partial<Pick<Dock, "name" | "lead" | "flags" | "notes" | "hours">>
> = {
  "marina-bay-harbor": {
    lead: 1,
    flags: ["last-pump", "still-open"],
    hours: "Daily 7:30am–5:30pm. Fri–Sun ship store 6am — store only, not the hose.",
    notes:
      "Last public pump at the Clear Lake mouth, Clear Lake Shores. Ship store page (30 Aug 2026) lists Daily 7:30am–5:30pm; Fri–Sun 6am is the store, not the hose. Waterway Guide 08/28/26 listed 87 and 93 as No Report This Week. 93 is the E0 hose. Does not sell diesel. Blank stays Call.",
  },
  "blue-marlin-seabrook": {
    name: "Blue Marlin Fuel Dock",
    lead: 2,
    flags: ["last-pump", "still-open"],
    notes:
      "Seabrook, west of SH 146. Waterway Guide 08/28/26: diesel $5.280, 87 $4.980, 93 $5.990 E0, tax included. Hours Daily 7am–6pm. Still open when they post hours.",
  },
  "south-shore-harbour": {
    name: "South Shore Harbour Fuel Pier",
    lead: 3,
    flags: ["still-open"],
    notes:
      "League City fuel pier. Waterway Guide 08/28/26: diesel $5.000, 89 $5.500, tax included. Non-ethanol: No. Hours Daily 8am–6pm (summer hours on marina site). Hours beat a posted price.",
  },
  "houston-yacht-club": {
    lead: 4,
    notes:
      "Club only. Members' dock, not a public pump. Waterway Guide listing: diesel Call, 89 Call. Last fuel update Never.",
  },
  "lakewood-yacht-club": {
    lead: 5,
    notes:
      "Club only. Private. Not a public pump. Waterway Guide lists diesel and gas as Call. Last fuel update 06/24/25.",
  },
  "watermans-harbor": {
    lead: 6,
    notes:
      "On Dickinson Bayou. Waterway Guide lists gas as Call, non-ethanol No, last fuel update Never. No diesel line on that listing.",
  },
  "galveston-yacht-marina": {
    lead: 7,
    notes:
      "Galveston Island, not the Clear Lake mouth. Marina homepage on 30 Aug 2026 posted Diesel $5.28, Unleaded $4.45, Non-Ethanol $5.79. Matches Waterway Guide 08/28/26.",
  },
  "key-largo-harbor": {
    lead: 1,
    notes:
      "Key Largo stretch. Waterway Guide: diesel Call, 87–93 Call, non-ethanol Yes. Last fuel update 08/26/2022. Call / unverified. Do not invent a 2026 price. Dock E0 is not the landside E10 hose.",
  },
  "marina-del-mar": {
    lead: 2,
  },
  "pilot-house-marina": {
    lead: 3,
  },
  "garden-cove-marina": {
    lead: 4,
    notes:
      "Key Largo. Waterway Guide: 90 Call, non-ethanol No (landside E10, not dock E0). Last fuel update 06/29/23. Marina site confirms gas; no pump price. Call.",
  },
  "ocean-reef-club": {
    lead: 5,
  },
  "mangrove-marina": {
    lead: 6,
  },
  "tavernier-creek": {
    lead: 7,
    notes:
      "Tavernier. Waterway Guide marina listing: gas Call, non-ethanol No (landside E10). Last fuel update Never. Call.",
  },
  "plantation-yacht-harbor": {
    lead: 20,
    notes:
      "Islamorada — a different run from Key Largo. Waterway Guide 08/24/26: diesel $6.000, 90 $5.659, tax included, non-ethanol Yes.",
  },
  islamarina: {
    lead: 21,
    notes:
      "Islamorada — a different run from Key Largo. Waterway Guide 08/28/26: diesel $5.450, 90 $5.590, tax included, non-ethanol Yes.",
  },
  "snake-creek-marina": {
    lead: 22,
    notes:
      "Islamorada — a different run from Key Largo. Listed on Waterway Guide as The Marina at Islamorada Yacht Club, now Snake Creek Marina. 08/28/26: does not sell diesel; 90 No Report This Week; non-ethanol Yes.",
  },
  "three-waters-marina": {
    lead: 23,
    notes:
      "Islamorada — a different run from Key Largo. Waterway Guide 08/28/26: diesel $6.250, 90 $5.500, tax included, non-ethanol Yes.",
  },
  "worldwide-sportsman": {
    lead: 24,
    notes:
      "Islamorada — a different run from Key Largo. Waterway Guide 08/28/26: diesel $4.840 tax not included (7.50%), 90 $5.170 tax included, non-ethanol Yes.",
  },
  "bud-n-marys": {
    lead: 25,
    notes:
      "Islamorada — a different run from Key Largo. Waterway Guide 08/28/26: diesel $6.290 (dyed diesel noted), 90 $6.190, tax included, non-ethanol Yes.",
  },
};

function homeDock(row: {
  id: string;
  name: string;
  city: string;
  lat: number;
  lng: number;
  phone: string;
  website: string;
  notes: string;
  access: DockAccess;
  lead: number;
  flags?: DockFlag[];
}): Dock {
  return {
    id: row.id,
    name: row.name,
    corridor: "upper-keys",
    region: "keys",
    city: row.city,
    state: "FL",
    lat: row.lat,
    lng: row.lng,
    phone: row.phone,
    hours: null,
    website: row.website,
    notes: row.notes,
    access: row.access,
    ethanol: "unknown",
    quotes: callQuotes(["90", "diesel"]),
    lastVerifiedAt: null,
    lastVerifiedSource: "marina site",
    sourceUrl: row.website,
    lead: row.lead,
    flags: row.flags,
  };
}

const HOME_ADDITIONS: Dock[] = [
  homeDock({
    id: "marina-del-mar",
    name: "Marina Del Mar",
    city: "Key Largo",
    lat: 25.0965,
    lng: -80.4378,
    phone: "(305) 451-4107",
    website: "https://www.marinadelmar.com/",
    notes:
      "Key Largo, next to the harbor. Public marina. Marketing page lists docks; no pump dollars. Call. We do not invent a price.",
    access: "public",
    lead: 2,
  }),
  homeDock({
    id: "ocean-reef-club",
    name: "Ocean Reef Club",
    city: "North Key Largo",
    lat: 25.3094,
    lng: -80.2778,
    phone: "(305) 367-2611",
    website: "https://www.oceanreef.com/",
    notes:
      "Members only. Not a public pump. Gated North Key Largo club. Call the club if you belong. We do not invent a price.",
    access: "members",
    lead: 5,
  }),
];

const ADDITIONS: Addition[] = [
  // Texas beyond Clear Lake / Galveston Bay. No Kemah Boardwalk weekend
  // routing. No Watergate / Waterford / Legend Point / Portofino — no fuel.
  {
    id: "cove-harbor-rockport",
    name: "Cove Harbor Marina",
    region: "texas",
    city: "Rockport",
    state: "TX",
    lat: 28.0324,
    lng: -97.0462,
    phone: "(361) 729-8381",
    website: "https://www.coveharbor.com/",
    notes:
      "Aransas Bay. Waterway Guide carries this dock on the Gulf report. Marina site has no live pump board (30 Aug 2026). Call.",
  },
  {
    id: "island-moorings",
    name: "Island Moorings Marina",
    region: "texas",
    city: "Port Aransas",
    state: "TX",
    lat: 27.8342,
    lng: -97.0721,
    phone: "(361) 749-4100",
    website: "https://www.islandmoorings.com/",
    notes: "Port Aransas basin. Public marina directory and marina site; no pump prices posted.",
  },
  {
    id: "port-aransas-city-marina",
    name: "Port Aransas City Harbor",
    region: "texas",
    city: "Port Aransas",
    state: "TX",
    lat: 27.8381,
    lng: -97.0614,
    phone: "(361) 749-4158",
    website: "https://www.cityofportaransas.org/",
    notes: "Municipal harbor. City pages list slips and services, not a fuel board.",
  },
  {
    id: "corpus-christi-marina",
    name: "Corpus Christi Municipal Marina",
    region: "texas",
    city: "Corpus Christi",
    state: "TX",
    lat: 27.7952,
    lng: -97.3906,
    phone: "(361) 826-3980",
    website: "https://www.cctexas.com/departments/marina",
    notes: "City marina on the downtown bayfront. Municipal site; call for fuel.",
  },
  {
    id: "south-padre-island-marina",
    name: "South Padre Island Marina",
    region: "texas",
    city: "South Padre Island",
    state: "TX",
    lat: 26.1034,
    lng: -97.1682,
    phone: "(956) 761-5443",
    website: null,
    notes: "Island wet slips on the Laguna Madre. Public harbor; no posted pump price found.",
  },
  {
    id: "sea-ranch-marina",
    name: "Sea Ranch Marina",
    region: "texas",
    city: "South Padre Island",
    state: "TX",
    lat: 26.0788,
    lng: -97.1589,
    phone: "(956) 761-4511",
    website: "https://searanchmarina.com/",
    notes: "Lower Laguna. Marina site lists fuel; no dollars on the page.",
  },
  {
    id: "freeport-municipal-harbor",
    name: "Freeport Municipal Harbor",
    region: "texas",
    city: "Freeport",
    state: "TX",
    lat: 28.9436,
    lng: -95.3082,
    phone: "(979) 233-3526",
    website: "https://www.freeport.tx.us/",
    notes: "City harbor on the Old Brazos. Call the dock.",
  },
  {
    id: "pleasure-island-marina",
    name: "Pleasure Island Marina",
    region: "texas",
    city: "Port Arthur",
    state: "TX",
    lat: 29.8664,
    lng: -93.9305,
    phone: "(409) 982-4675",
    website: null,
    notes: "Sabine Lake / Pleasure Island. Public harbor listing; no pump board found.",
  },

  // Louisiana
  {
    id: "orleans-marina",
    name: "Orleans Marina",
    region: "louisiana",
    city: "New Orleans",
    state: "LA",
    lat: 30.0271,
    lng: -90.1134,
    phone: "(504) 288-2351",
    website: "https://www.orleansmarina.com/",
    notes: "West End on Lake Pontchartrain. Marina site; call for fuel.",
  },
  {
    id: "municipal-yacht-harbor-nola",
    name: "New Orleans Municipal Yacht Harbor",
    region: "louisiana",
    city: "New Orleans",
    state: "LA",
    lat: 30.0262,
    lng: -90.1186,
    phone: "(504) 288-1431",
    website: "https://www.noych.org/",
    notes: "City yacht harbor, West End. Public listing; no pump prices.",
  },
  {
    id: "cypress-cove-venice",
    name: "Cypress Cove Marina",
    region: "louisiana",
    city: "Venice",
    state: "LA",
    lat: 29.2486,
    lng: -89.3674,
    phone: "(985) 534-9289",
    website: "https://www.cypresscovemarina.com/",
    notes: "Birdfoot launch. Site lists fuel and ice; no posted dollars.",
  },
  {
    id: "venice-marina",
    name: "Venice Marina",
    region: "louisiana",
    city: "Venice",
    state: "LA",
    lat: 29.2772,
    lng: -89.3548,
    phone: "(985) 534-9357",
    website: "https://www.venicemarina.com/",
    notes: "Venice jump-off. Marina site; call the dock.",
  },
  {
    id: "bridgeside-grand-isle",
    name: "Bridgeside Marina",
    region: "louisiana",
    city: "Grand Isle",
    state: "LA",
    lat: 29.2384,
    lng: -89.9871,
    phone: "(985) 787-2412",
    website: null,
    notes: "Grand Isle bridge side. Public marina listing; call ahead.",
  },
  {
    id: "harborwalk-lake-charles",
    name: "Harborwalk Marina",
    region: "louisiana",
    city: "Lake Charles",
    state: "LA",
    lat: 30.2264,
    lng: -93.2281,
    phone: "(337) 433-6511",
    website: null,
    notes: "Contraband Bayou downtown. City / tourism listings; no pump board.",
  },
  {
    id: "calcasieu-point-marina",
    name: "Calcasieu Point Marina",
    region: "louisiana",
    city: "Lake Charles",
    state: "LA",
    lat: 30.1188,
    lng: -93.3324,
    phone: "(337) 474-0248",
    website: null,
    notes: "Calcasieu ship channel. Public directory; call.",
  },

  // Mississippi
  {
    id: "gulfport-small-craft-harbor",
    name: "Gulfport Small Craft Harbor",
    region: "mississippi",
    city: "Gulfport",
    state: "MS",
    lat: 30.3602,
    lng: -89.0864,
    phone: "(228) 868-5710",
    website: "https://www.gulfport-ms.gov/",
    notes: "City small-craft harbor. Municipal pages; call for fuel.",
  },
  {
    id: "biloxi-small-craft-harbor",
    name: "Biloxi Small Craft Harbor",
    region: "mississippi",
    city: "Biloxi",
    state: "MS",
    lat: 30.3928,
    lng: -88.8852,
    phone: "(228) 436-9324",
    website: "https://www.biloxi.ms.us/",
    notes: "Downtown Biloxi harbor. City listing; no posted pump price.",
  },
  {
    id: "ocean-springs-harbor",
    name: "Ocean Springs Harbor",
    region: "mississippi",
    city: "Ocean Springs",
    state: "MS",
    lat: 30.4112,
    lng: -88.8276,
    phone: "(228) 875-6712",
    website: "https://www.oceansprings-ms.gov/",
    notes: "Municipal harbor. Call the harbor master.",
  },
  {
    id: "bay-st-louis-harbor",
    name: "Bay St. Louis Harbor",
    region: "mississippi",
    city: "Bay St. Louis",
    state: "MS",
    lat: 30.3084,
    lng: -89.3261,
    phone: "(228) 466-8961",
    website: "https://www.baystlouis-ms.gov/",
    notes: "City harbor on the bay. Public listing; call.",
  },
  {
    id: "pass-christian-harbor",
    name: "Pass Christian Harbor",
    region: "mississippi",
    city: "Pass Christian",
    state: "MS",
    lat: 30.3152,
    lng: -89.2474,
    phone: "(228) 452-3312",
    website: "https://www.pass-christian.com/",
    notes: "Municipal harbor. City site; no fuel board.",
  },

  // Alabama
  {
    id: "orange-beach-marina",
    name: "Orange Beach Marina",
    region: "alabama",
    city: "Orange Beach",
    state: "AL",
    lat: 30.2786,
    lng: -87.5724,
    phone: "(251) 981-4207",
    website: "https://www.orangebeachmarina.com/",
    notes: "Inland waterway. Marina site lists fuel; no pump dollars posted.",
  },
  {
    id: "sportsman-marina",
    name: "Sportsman Marina",
    region: "alabama",
    city: "Orange Beach",
    state: "AL",
    lat: 30.2789,
    lng: -87.5568,
    phone: "(251) 981-6247",
    website: "https://www.sportsmanmarina.com/",
    notes: "Orange Beach. Site confirms gas and diesel; call for today's board.",
  },
  {
    id: "the-wharf-marina",
    name: "The Wharf Marina",
    region: "alabama",
    city: "Orange Beach",
    state: "AL",
    lat: 30.2904,
    lng: -87.6282,
    phone: "(251) 224-1900",
    website: "https://www.thewharforangebeach.com/",
    notes: "Wharf complex slips. Marketing site; no live prices.",
  },
  {
    id: "homeport-marina-gulf-shores",
    name: "Homeport Marina",
    region: "alabama",
    city: "Gulf Shores",
    state: "AL",
    lat: 30.2536,
    lng: -87.6871,
    phone: "(251) 968-4528",
    website: null,
    notes: "Gulf Shores / ICW. Public marina listing; call.",
  },
  {
    id: "dog-river-marina",
    name: "Dog River Marina",
    region: "alabama",
    city: "Mobile",
    state: "AL",
    lat: 30.5648,
    lng: -88.0882,
    phone: "(251) 471-5449",
    website: "https://www.dogrivermarina.com/",
    notes: "Mobile's Dog River. Yard and fuel dock; no posted pump price.",
  },
  {
    id: "fly-creek-marina",
    name: "Fly Creek Marina",
    region: "alabama",
    city: "Fairhope",
    state: "AL",
    lat: 30.5458,
    lng: -87.9114,
    phone: "(251) 928-1288",
    website: null,
    notes: "Eastern Shore, Fly Creek. Public listing; call.",
  },

  // West Florida
  {
    id: "destin-harbor-boardwalk",
    name: "Destin Harbor Boardwalk Marina",
    region: "west-florida",
    city: "Destin",
    state: "FL",
    lat: 30.3918,
    lng: -86.5116,
    phone: "(850) 337-7210",
    website: "https://www.destinharborboardwalk.com/",
    notes: "HarborWalk. Transient fuel on the harbor; no dollars on the page.",
  },
  {
    id: "panama-city-marina",
    name: "Panama City Marina",
    region: "west-florida",
    city: "Panama City",
    state: "FL",
    lat: 30.1524,
    lng: -85.6618,
    phone: "(850) 872-3840",
    website: "https://www.panamacity.gov/marina",
    notes: "City marina downtown. Municipal site; call the dock.",
  },
  {
    id: "apalachicola-city-marina",
    name: "Apalachicola City Marina",
    region: "west-florida",
    city: "Apalachicola",
    state: "FL",
    lat: 29.7256,
    lng: -84.9831,
    phone: "(850) 653-9524",
    website: "https://www.cityofapalachicola.com/",
    notes: "Water Street basin. City harbor; call.",
  },
  {
    id: "marina-jack-sarasota",
    name: "Marina Jack",
    region: "west-florida",
    city: "Sarasota",
    state: "FL",
    lat: 27.3324,
    lng: -82.5458,
    phone: "(941) 365-4232",
    website: "https://www.marinajack.com/",
    notes: "Downtown Sarasota. Site lists fuel; no pump board.",
  },
  {
    id: "st-pete-municipal-marina",
    name: "St. Petersburg Municipal Marina",
    region: "west-florida",
    city: "St. Petersburg",
    state: "FL",
    lat: 27.7712,
    lng: -82.6284,
    phone: "(727) 893-7329",
    website: "https://www.stpete.org/marina",
    notes: "City marina on the downtown waterfront. Call for fuel.",
  },
  {
    id: "clearwater-beach-marina",
    name: "Clearwater Beach Marina",
    region: "west-florida",
    city: "Clearwater",
    state: "FL",
    lat: 27.9776,
    lng: -82.8271,
    phone: "(727) 462-6954",
    website: "https://www.myclearwater.com/",
    notes: "City beach marina. Municipal listing; call.",
  },
  {
    id: "naples-city-dock",
    name: "Naples City Dock",
    region: "west-florida",
    city: "Naples",
    state: "FL",
    lat: 26.1362,
    lng: -81.7884,
    phone: "(239) 213-3070",
    website: "https://www.naplesgov.com/",
    notes: "Municipal dock at 12th Avenue South. City pages; call for fuel.",
  },
  {
    id: "moss-marine-ft-myers-beach",
    name: "Moss Marine",
    region: "west-florida",
    city: "Fort Myers Beach",
    state: "FL",
    lat: 26.4558,
    lng: -81.9532,
    phone: "(239) 463-6137",
    website: "https://www.mossmarine.com/",
    notes: "Matanzas Pass. Yard and fuel; no live prices on the site.",
  },
  {
    id: "tarpon-point-marina",
    name: "Tarpon Point Marina",
    region: "west-florida",
    city: "Cape Coral",
    state: "FL",
    lat: 26.5486,
    lng: -82.0084,
    phone: "(239) 549-4900",
    website: "https://www.tarponpoint.com/",
    notes: "Cape Coral / Caloosahatchee. Resort marina; call the fuel dock.",
  },

  // Keys beyond Upper Keys home set
  {
    id: "faro-blanco-marathon",
    name: "Faro Blanco Resort & Yacht Club",
    region: "keys",
    city: "Marathon",
    state: "FL",
    lat: 24.7114,
    lng: -81.0952,
    phone: "(305) 289-0000",
    website: "https://www.faroblancoresort.com/",
    notes: "Marathon bayside. Resort marina; no pump board on the marketing page.",
  },
  {
    id: "marathon-marina",
    name: "Marathon Marina",
    region: "keys",
    city: "Marathon",
    state: "FL",
    lat: 24.7096,
    lng: -81.0941,
    phone: "(305) 743-6575",
    website: "https://www.marathonmarina.com/",
    notes: "Boot Key Harbor side. Site lists fuel; call for today's number.",
  },
  {
    id: "hawks-cay-marina",
    name: "Hawks Cay Marina",
    region: "keys",
    city: "Duck Key",
    state: "FL",
    lat: 24.7752,
    lng: -80.9094,
    phone: "(305) 743-9000",
    website: "https://www.hawkscay.com/",
    notes: "Duck Key resort basin. Call the dockhouse.",
  },
  {
    id: "key-west-bight-marina",
    name: "Key West Bight Marina",
    region: "keys",
    city: "Key West",
    state: "FL",
    lat: 24.5618,
    lng: -81.8002,
    phone: "(305) 809-3981",
    website: "https://www.cityofkeywest-fl.gov/",
    notes: "Historic Bight, city docks. Municipal pages; call for fuel.",
  },
  {
    id: "conch-harbor-marina",
    name: "Conch Harbor Marina",
    region: "keys",
    city: "Key West",
    state: "FL",
    lat: 24.5626,
    lng: -81.8018,
    phone: "(305) 294-8704",
    website: "https://www.conchharbormarina.com/",
    notes: "Key West Bight. Marina site; no live pump prices.",
  },
  {
    id: "galleon-marina",
    name: "The Galleon Marina",
    region: "keys",
    city: "Key West",
    state: "FL",
    lat: 24.5574,
    lng: -81.8076,
    phone: "(305) 292-1292",
    website: "https://www.galleonresort.com/",
    notes: "Old Town waterfront. Resort marina; call.",
  },
  {
    id: "stock-island-marina",
    name: "Stock Island Marina Village",
    region: "keys",
    city: "Stock Island",
    state: "FL",
    lat: 24.5692,
    lng: -81.7358,
    phone: "(305) 294-2288",
    website: "https://www.stockislandmarina.com/",
    notes: "East of Key West. Large public marina; no posted dollars.",
  },

  // East Florida
  {
    id: "miami-beach-marina",
    name: "Miami Beach Marina",
    region: "east-florida",
    city: "Miami Beach",
    state: "FL",
    lat: 25.7704,
    lng: -80.1398,
    phone: "(305) 673-6000",
    website: "https://www.miamibeachmarina.com/",
    notes: "Government Cut. Marina site lists fuel; call for the board.",
  },
  {
    id: "crandon-park-marina",
    name: "Crandon Park Marina",
    region: "east-florida",
    city: "Key Biscayne",
    state: "FL",
    lat: 25.7216,
    lng: -80.1552,
    phone: "(305) 361-1281",
    website: "https://www.miamidade.gov/parks/crandon-marina.asp",
    notes: "Miami-Dade park marina. County pages; call.",
  },
  {
    id: "dinner-key-marina",
    name: "Dinner Key Marina",
    region: "east-florida",
    city: "Coconut Grove",
    state: "FL",
    lat: 25.7268,
    lng: -80.2346,
    phone: "(305) 579-6980",
    website: "https://www.miami.gov/",
    notes: "City of Miami marina. Municipal listing; call the dock.",
  },
  {
    id: "bahia-mar-fort-lauderdale",
    name: "Bahia Mar Yachting Center",
    region: "east-florida",
    city: "Fort Lauderdale",
    state: "FL",
    lat: 26.1182,
    lng: -80.1076,
    phone: "(954) 627-6309",
    website: "https://www.bahiamarhotel.com/",
    notes: "A1A / Intracoastal. Fuel dock on site; no pump prices posted.",
  },
  {
    id: "las-olas-marina",
    name: "Las Olas Marina",
    region: "east-florida",
    city: "Fort Lauderdale",
    state: "FL",
    lat: 26.1196,
    lng: -80.1088,
    phone: "(954) 828-7200",
    website: "https://www.fortlauderdale.gov/",
    notes: "City marina at the inlet. Municipal pages; call.",
  },
  {
    id: "sailfish-marina-palm-beach",
    name: "Sailfish Marina Resort",
    region: "east-florida",
    city: "Palm Beach Shores",
    state: "FL",
    lat: 26.7732,
    lng: -80.0418,
    phone: "(561) 844-1724",
    website: "https://www.sailfishmarina.com/",
    notes: "Lake Worth Inlet. Classic sportfish dock; call for fuel.",
  },
  {
    id: "riviera-beach-marina",
    name: "Riviera Beach Marina",
    region: "east-florida",
    city: "Riviera Beach",
    state: "FL",
    lat: 26.7694,
    lng: -80.0496,
    phone: "(561) 842-7806",
    website: "https://www.rivierabch.com/",
    notes: "Municipal marina. City site; no pump board.",
  },
  {
    id: "fort-pierce-city-marina",
    name: "Fort Pierce City Marina",
    region: "east-florida",
    city: "Fort Pierce",
    state: "FL",
    lat: 27.4472,
    lng: -80.3234,
    phone: "(772) 464-1245",
    website: "https://www.cityoffortpierce.com/",
    notes: "Downtown municipal docks. Call the marina office.",
  },
  {
    id: "vera-beach-municipal-marina",
    name: "Vero Beach Municipal Marina",
    region: "east-florida",
    city: "Vero Beach",
    state: "FL",
    lat: 27.6348,
    lng: -80.3726,
    phone: "(772) 978-4960",
    website: "https://www.covb.org/",
    notes: "City marina on the ICW. Municipal listing; call.",
  },
  {
    id: "port-canaveral-sunrise",
    name: "Sunrise Marina at Port Canaveral",
    region: "east-florida",
    city: "Cape Canaveral",
    state: "FL",
    lat: 28.4106,
    lng: -80.6272,
    phone: "(321) 783-9535",
    website: null,
    notes: "Port Canaveral basin. Public marina listing; call.",
  },
  {
    id: "daytona-beach-marina",
    name: "Daytona Beach Municipal Marina",
    region: "east-florida",
    city: "Daytona Beach",
    state: "FL",
    lat: 29.2186,
    lng: -81.0174,
    phone: "(386) 671-3630",
    website: "https://www.codb.us/",
    notes: "Halifax River city docks. Call the marina.",
  },
  {
    id: "st-augustine-municipal-marina",
    name: "St. Augustine Municipal Marina",
    region: "east-florida",
    city: "St. Augustine",
    state: "FL",
    lat: 29.8914,
    lng: -81.3098,
    phone: "(904) 825-1026",
    website: "https://www.citystaug.com/marina",
    notes: "City marina under the Bridge of Lions. Municipal site; call.",
  },
  {
    id: "fernandina-harbor-marina",
    name: "Fernandina Harbor Marina",
    region: "east-florida",
    city: "Fernandina Beach",
    state: "FL",
    lat: 30.6712,
    lng: -81.4654,
    phone: "(904) 491-2090",
    website: "https://www.fbfl.us/",
    notes: "Amelia Island waterfront. City / marina pages; call for fuel.",
  },

  // Georgia
  {
    id: "golden-isles-marina",
    name: "Golden Isles Marina",
    region: "georgia",
    city: "St. Simons Island",
    state: "GA",
    lat: 31.1682,
    lng: -81.4068,
    phone: "(912) 634-1128",
    website: "https://www.goldenislesmarina.com/",
    notes: "Frederica River. Marina site lists fuel; no pump dollars.",
  },
  {
    id: "brunswick-landing-marina",
    name: "Brunswick Landing Marina",
    region: "georgia",
    city: "Brunswick",
    state: "GA",
    lat: 31.1496,
    lng: -81.4972,
    phone: "(912) 262-9264",
    website: "https://www.brunswicklandingmarina.com/",
    notes: "East River downtown. Site; call the dock.",
  },
  {
    id: "thunderbolt-marina",
    name: "Thunderbolt Marine",
    region: "georgia",
    city: "Thunderbolt",
    state: "GA",
    lat: 32.0364,
    lng: -81.0518,
    phone: "(912) 352-4931",
    website: "https://www.thunderboltmarine.us/",
    notes: "Wilmington River yard. Fuel on site; no posted price.",
  },
  {
    id: "isle-of-hope-marina",
    name: "Isle of Hope Marina",
    region: "georgia",
    city: "Savannah",
    state: "GA",
    lat: 31.9816,
    lng: -81.0564,
    phone: "(912) 354-8187",
    website: "https://www.isleofhopemarina.com/",
    notes: "Skidaway River. Long-running public marina; call.",
  },
  {
    id: "bahia-bleu-savannah",
    name: "Bahia Bleu Marina",
    region: "georgia",
    city: "Thunderbolt",
    state: "GA",
    lat: 32.0338,
    lng: -81.0496,
    phone: "(912) 354-2283",
    website: null,
    notes: "Thunderbolt waterfront. Public listing; call.",
  },

  // South Carolina
  {
    id: "charleston-city-marina",
    name: "Charleston City Marina",
    region: "south-carolina",
    city: "Charleston",
    state: "SC",
    lat: 32.7764,
    lng: -79.9532,
    phone: "(843) 722-4968",
    website: "https://www.charlestoncitymarina.com/",
    notes: "Ashley River. MegaDock and fuel; no live pump board.",
  },
  {
    id: "charleston-harbor-marina",
    name: "Charleston Harbor Marina",
    region: "south-carolina",
    city: "Mount Pleasant",
    state: "SC",
    lat: 32.7902,
    lng: -79.9054,
    phone: "(843) 284-7485",
    website: "https://www.charlestonharbormarina.com/",
    notes: "Patriots Point. Marina site; call for fuel.",
  },
  {
    id: "beaufort-downtown-marina",
    name: "Downtown Marina of Beaufort",
    region: "south-carolina",
    city: "Beaufort",
    state: "SC",
    lat: 32.4296,
    lng: -80.6748,
    phone: "(843) 524-4422",
    website: "https://www.downtownmarinabeaufort.com/",
    notes: "Beaufort River. Transient docks; call.",
  },
  {
    id: "shelter-cove-harbour",
    name: "Shelter Cove Harbour",
    region: "south-carolina",
    city: "Hilton Head Island",
    state: "SC",
    lat: 32.1814,
    lng: -80.7256,
    phone: "(843) 842-7001",
    website: "https://www.sheltercovehhi.com/",
    notes: "Broad Creek. Resort harbor; no posted pump price.",
  },
  {
    id: "harbour-town-yacht-basin",
    name: "Harbour Town Yacht Basin",
    region: "south-carolina",
    city: "Hilton Head Island",
    state: "SC",
    lat: 32.1392,
    lng: -80.8124,
    phone: "(843) 671-2704",
    website: "https://www.seapines.com/",
    notes: "Sea Pines lighthouse basin. Call the yacht basin.",
  },
  {
    id: "georgetown-harborwalk",
    name: "Harborwalk Marina",
    region: "south-carolina",
    city: "Georgetown",
    state: "SC",
    lat: 33.3672,
    lng: -79.2814,
    phone: "(843) 546-4250",
    website: null,
    notes: "Georgetown waterfront. Public listing; call.",
  },

  // North Carolina
  {
    id: "beaufort-docks-nc",
    name: "Beaufort Docks",
    region: "north-carolina",
    city: "Beaufort",
    state: "NC",
    lat: 34.7178,
    lng: -76.6638,
    phone: "(252) 728-2503",
    website: "https://www.beaufortdocks.com/",
    notes: "Taylor's Creek downtown. Classic transient docks; call for fuel.",
  },
  {
    id: "morehead-city-waterfront",
    name: "Morehead City Waterfront",
    region: "north-carolina",
    city: "Morehead City",
    state: "NC",
    lat: 34.7196,
    lng: -76.7142,
    phone: "(252) 726-6862",
    website: "https://www.moreheadcitync.org/",
    notes: "City waterfront slips. Municipal / tourism listings; call.",
  },
  {
    id: "hatteras-harbor-marina",
    name: "Hatteras Harbor Marina",
    region: "north-carolina",
    city: "Hatteras",
    state: "NC",
    lat: 35.2084,
    lng: -75.6902,
    phone: "(252) 986-2166",
    website: "https://www.hatterasharbor.com/",
    notes: "Hatteras village. Sportfish docks; call the fuel dock.",
  },
  {
    id: "oregon-inlet-fishing-center",
    name: "Oregon Inlet Fishing Center",
    region: "north-carolina",
    city: "Nags Head",
    state: "NC",
    lat: 35.7688,
    lng: -75.5264,
    phone: "(252) 441-6301",
    website: "https://www.oregon-inlet.com/",
    notes: "National Park Service concession at the inlet. Call.",
  },
  {
    id: "manteo-waterfront-marina",
    name: "Manteo Waterfront Marina",
    region: "north-carolina",
    city: "Manteo",
    state: "NC",
    lat: 35.9082,
    lng: -75.6696,
    phone: "(252) 468-1001",
    website: null,
    notes: "Shallowbag Bay. Public waterfront listing; call.",
  },
  {
    id: "southport-marina-nc",
    name: "Southport Marina",
    region: "north-carolina",
    city: "Southport",
    state: "NC",
    lat: 33.9168,
    lng: -78.0186,
    phone: "(910) 457-9900",
    website: "https://www.southport-marina.com/",
    notes: "Cape Fear mouth. Marina site; no pump dollars posted.",
  },
  {
    id: "wrightsville-seapath",
    name: "Seapath Yacht Club",
    region: "north-carolina",
    city: "Wrightsville Beach",
    state: "NC",
    lat: 34.2086,
    lng: -77.7964,
    phone: "(910) 256-3747",
    website: "https://www.seapath.com/",
    notes: "Banks Channel. Yacht club / marina; call.",
    access: "members",
  },
  {
    id: "carolina-beach-state-marina",
    name: "Carolina Beach State Park Marina",
    region: "north-carolina",
    city: "Carolina Beach",
    state: "NC",
    lat: 34.0482,
    lng: -77.9126,
    phone: "(910) 458-7770",
    website: "https://www.ncparks.gov/carolina-beach-state-park",
    notes: "State park marina on the Cape Fear. Park pages; call.",
  },

  // Virginia
  {
    id: "hampton-public-piers",
    name: "Hampton Public Piers",
    region: "virginia",
    city: "Hampton",
    state: "VA",
    lat: 37.0254,
    lng: -76.3448,
    phone: "(757) 727-1276",
    website: "https://hampton.gov/",
    notes: "Downtown Hampton waterfront. City piers; call for fuel nearby.",
  },
  {
    id: "waterside-marina-norfolk",
    name: "Waterside Marina",
    region: "virginia",
    city: "Norfolk",
    state: "VA",
    lat: 36.8436,
    lng: -76.2902,
    phone: "(757) 625-3625",
    website: "https://www.watersidemarina.com/",
    notes: "Elizabeth River downtown. Marina site; call.",
  },
  {
    id: "ocean-marine-portsmouth",
    name: "Ocean Marine Yacht Center",
    region: "virginia",
    city: "Portsmouth",
    state: "VA",
    lat: 36.8352,
    lng: -76.2974,
    phone: "(757) 399-2920",
    website: "https://www.oceanmarinenc.com/",
    notes: "Portsmouth waterfront yard. Fuel on site; no posted price.",
  },
  {
    id: "rudee-inlet-station",
    name: "Rudee Inlet Station Marina",
    region: "virginia",
    city: "Virginia Beach",
    state: "VA",
    lat: 36.8304,
    lng: -75.9736,
    phone: "(757) 422-2999",
    website: null,
    notes: "Rudee Inlet. Public marina listing; call.",
  },
  {
    id: "cape-charles-harbor",
    name: "Cape Charles Harbor",
    region: "virginia",
    city: "Cape Charles",
    state: "VA",
    lat: 37.2678,
    lng: -76.0164,
    phone: "(757) 331-2357",
    website: "https://www.capecharles.org/",
    notes: "Eastern Shore harbor. Town pages; call the harbor master.",
  },
  {
    id: "yorktown-riverwalk",
    name: "Yorktown Riverwalk Landing",
    region: "virginia",
    city: "Yorktown",
    state: "VA",
    lat: 37.2348,
    lng: -76.5086,
    phone: "(757) 890-3370",
    website: "https://www.yorkcounty.gov/",
    notes: "County docks on the York. Transient; call about fuel nearby.",
  },

  // Maryland
  {
    id: "annapolis-city-dock",
    name: "Annapolis City Dock",
    region: "maryland",
    city: "Annapolis",
    state: "MD",
    lat: 38.9766,
    lng: -76.4848,
    phone: "(410) 263-7973",
    website: "https://www.annapolis.gov/",
    notes: "Ego Alley / Market House. City dock; fuel is at nearby harbors — call.",
  },
  {
    id: "port-annapolis-marina",
    name: "Port Annapolis Marina",
    region: "maryland",
    city: "Annapolis",
    state: "MD",
    lat: 38.9532,
    lng: -76.4842,
    phone: "(410) 269-1993",
    website: "https://www.portannapolis.com/",
    notes: "Back Creek. Full-service marina; call for fuel.",
  },
  {
    id: "herrington-harbour-north",
    name: "Herrington Harbour North",
    region: "maryland",
    city: "Deale",
    state: "MD",
    lat: 38.7916,
    lng: -76.5418,
    phone: "(410) 867-4343",
    website: "https://www.herringtonharbour.com/",
    notes: "West River / Tracey's Creek. Large public marina; no pump board on the site.",
  },
  {
    id: "zahnisers-solomons",
    name: "Zahniser's Yachting Center",
    region: "maryland",
    city: "Solomons",
    state: "MD",
    lat: 38.3174,
    lng: -76.4536,
    phone: "(410) 326-2166",
    website: "https://www.zahnisers.com/",
    notes: "Patuxent River. Classic Solomons dock; call.",
  },
  {
    id: "white-marlin-marina",
    name: "White Marlin Marina",
    region: "maryland",
    city: "Ocean City",
    state: "MD",
    lat: 38.3286,
    lng: -75.0912,
    phone: "(410) 289-6470",
    website: "https://www.whitemarlinmarina.com/",
    notes: "Ocean City inlet. Sportfish docks; call for fuel.",
  },
  {
    id: "st-michaels-harbour-inn",
    name: "St. Michaels Harbour Inn Marina",
    region: "maryland",
    city: "St. Michaels",
    state: "MD",
    lat: 38.7854,
    lng: -76.2238,
    phone: "(410) 745-9001",
    website: "https://www.harbourinn.com/",
    notes: "Miles River. Inn marina; call the dockhouse.",
  },

  // New Jersey
  {
    id: "canyon-club-cape-may",
    name: "Canyon Club Resort Marina",
    region: "new-jersey",
    city: "Cape May",
    state: "NJ",
    lat: 38.9486,
    lng: -74.9068,
    phone: "(609) 884-0199",
    website: "https://www.canyonclubmarina.com/",
    notes: "Cape May harbor. Resort marina; call for fuel.",
  },
  {
    id: "utschs-marina",
    name: "Utsch's Marina",
    region: "new-jersey",
    city: "Cape May",
    state: "NJ",
    lat: 38.9498,
    lng: -74.9014,
    phone: "(609) 884-2051",
    website: "https://www.utschsmarina.com/",
    notes: "Cape May. Long-running yard and fuel dock; no posted dollars.",
  },
  {
    id: "farley-state-marina",
    name: "Senator Frank S. Farley State Marina",
    region: "new-jersey",
    city: "Atlantic City",
    state: "NJ",
    lat: 39.3764,
    lng: -74.4292,
    phone: "(609) 441-8482",
    website: "https://www.golden-nugget.com/",
    notes: "Clam Creek / Golden Nugget. State marina; call the fuel dock.",
  },
  {
    id: "hoffmans-point-pleasant",
    name: "Hoffman's Marina",
    region: "new-jersey",
    city: "Brielle",
    state: "NJ",
    lat: 40.1076,
    lng: -74.0518,
    phone: "(732) 528-6160",
    website: "https://www.hoffmansmarina.com/",
    notes: "Manasquan River. Public marina; call.",
  },
  {
    id: "atlantic-highlands-municipal",
    name: "Atlantic Highlands Municipal Harbor",
    region: "new-jersey",
    city: "Atlantic Highlands",
    state: "NJ",
    lat: 40.4138,
    lng: -74.0356,
    phone: "(732) 291-1670",
    website: "https://www.ahnj.com/",
    notes: "Sandy Hook Bay. Municipal harbor; call.",
  },
  {
    id: "liberty-landing-marina",
    name: "Liberty Landing Marina",
    region: "new-jersey",
    city: "Jersey City",
    state: "NJ",
    lat: 40.7108,
    lng: -74.0486,
    phone: "(201) 985-8000",
    website: "https://www.libertylandingmarina.com/",
    notes: "Hudson, Liberty State Park. Transient fuel; no pump board on the site.",
  },

  // New York
  {
    id: "montauk-marine-basin",
    name: "Montauk Marine Basin",
    region: "new-york",
    city: "Montauk",
    state: "NY",
    lat: 41.0716,
    lng: -71.9348,
    phone: "(631) 668-5900",
    website: "https://www.montaukmarinebasin.com/",
    notes: "Montauk Harbor. Classic canyon dock; call for fuel.",
  },
  {
    id: "star-island-yacht-club",
    name: "Star Island Yacht Club",
    region: "new-york",
    city: "Montauk",
    state: "NY",
    lat: 41.0732,
    lng: -71.9364,
    phone: "(631) 668-5052",
    website: "https://www.starislandyc.com/",
    notes: "Lake Montauk. Yacht club marina; call.",
  },
  {
    id: "greenport-docks",
    name: "Mitchell Park Marina",
    region: "new-york",
    city: "Greenport",
    state: "NY",
    lat: 41.1034,
    lng: -72.3596,
    phone: "(631) 477-2200",
    website: "https://www.villageofgreenport.org/",
    notes: "Village waterfront. Municipal marina; call about fuel nearby.",
  },
  {
    id: "sag-harbor-yacht-club",
    name: "Sag Harbor Yacht Club",
    region: "new-york",
    city: "Sag Harbor",
    state: "NY",
    lat: 41.0028,
    lng: -72.2954,
    phone: "(631) 725-0567",
    website: "https://www.sagharboryc.com/",
    notes: "Sag Harbor cove. Club docks; call.",
    access: "members",
  },
  {
    id: "freeport-hudson-canal",
    name: "Freeport Municipal Marina",
    region: "new-york",
    city: "Freeport",
    state: "NY",
    lat: 40.6348,
    lng: -73.5816,
    phone: "(516) 378-8100",
    website: "https://www.freeportny.gov/",
    notes: "Nautical Mile / Woodcleft. Village marina; call.",
  },
  {
    id: "great-kills-yacht-club",
    name: "Great Kills Yacht Club",
    region: "new-york",
    city: "Staten Island",
    state: "NY",
    lat: 40.5436,
    lng: -74.1338,
    phone: "(718) 356-2267",
    website: null,
    notes: "Great Kills Harbor. Club / public listings; call.",
    access: "members",
  },

  // New England
  {
    id: "mystic-shipyard",
    name: "Mystic Shipyard",
    region: "new-england",
    city: "Mystic",
    state: "CT",
    lat: 41.3498,
    lng: -71.9632,
    phone: "(860) 536-6588",
    website: "https://www.mysticshipyard.com/",
    notes: "Mystic River. Yard and fuel; no posted pump price.",
  },
  {
    id: "saybrook-point-marina",
    name: "Saybrook Point Marina",
    region: "new-england",
    city: "Old Saybrook",
    state: "CT",
    lat: 41.2836,
    lng: -72.3524,
    phone: "(860) 395-3080",
    website: "https://www.saybrook.com/",
    notes: "Connecticut River mouth. Resort marina; call.",
  },
  {
    id: "brewer-yacht-haven",
    name: "Brewer Yacht Haven Marina",
    region: "new-england",
    city: "Stamford",
    state: "CT",
    lat: 41.0386,
    lng: -73.5348,
    phone: "(203) 359-4500",
    website: "https://byy.com/",
    notes: "Stamford Harbor. Brewer yard; call the fuel dock.",
  },
  {
    id: "newport-yachting-center",
    name: "Newport Yachting Center",
    region: "new-england",
    city: "Newport",
    state: "RI",
    lat: 41.4862,
    lng: -71.3164,
    phone: "(401) 847-9040",
    website: "https://www.newportyachtingcenter.com/",
    notes: "America's Cup Avenue. Transient docks; call for fuel nearby.",
  },
  {
    id: "goat-island-marina",
    name: "Goat Island Marina",
    region: "new-england",
    city: "Newport",
    state: "RI",
    lat: 41.4916,
    lng: -71.3278,
    phone: "(401) 849-5655",
    website: "https://www.goatislandmarina.com/",
    notes: "Newport Harbor west. Marina site; call.",
  },
  {
    id: "paynes-dock-block-island",
    name: "Payne's Dock",
    region: "new-england",
    city: "New Shoreham",
    state: "RI",
    lat: 41.1738,
    lng: -71.5572,
    phone: "(401) 466-5572",
    website: null,
    notes: "Block Island New Harbor. Public dock listing; call.",
  },
  {
    id: "constitution-marina",
    name: "Constitution Marina",
    region: "new-england",
    city: "Boston",
    state: "MA",
    lat: 42.3724,
    lng: -71.0568,
    phone: "(617) 241-9640",
    website: "https://www.constitutionmarina.com/",
    notes: "Charlestown Navy Yard. Transient marina; call about fuel.",
  },
  {
    id: "hyannis-marina",
    name: "Hyannis Marina",
    region: "new-england",
    city: "Hyannis",
    state: "MA",
    lat: 41.6508,
    lng: -70.2806,
    phone: "(508) 790-4000",
    website: "https://www.hyannismarina.com/",
    notes: "Lewis Bay. Cape Cod fuel dock; no posted dollars.",
  },
  {
    id: "nantucket-boat-basin",
    name: "Nantucket Boat Basin",
    region: "new-england",
    city: "Nantucket",
    state: "MA",
    lat: 41.2856,
    lng: -70.0964,
    phone: "(508) 325-1355",
    website: "https://www.nantucketboatbasin.com/",
    notes: "Town pier basin. Marina site; call for fuel.",
  },
  {
    id: "vineyard-haven-marina",
    name: "Vineyard Haven Marina",
    region: "new-england",
    city: "Vineyard Haven",
    state: "MA",
    lat: 41.4562,
    lng: -70.5984,
    phone: "(508) 693-0720",
    website: null,
    notes: "Martha's Vineyard harbor. Public listing; call.",
  },
  {
    id: "plymouth-town-wharf",
    name: "Plymouth Town Wharf",
    region: "new-england",
    city: "Plymouth",
    state: "MA",
    lat: 41.9602,
    lng: -70.6624,
    phone: "(508) 830-4096",
    website: "https://www.plymouth-ma.gov/",
    notes: "Town wharf on the harbor. Municipal pages; call.",
  },
  {
    id: "gloucester-harbor-loop",
    name: "Gloucester House / Harbor Loop",
    region: "new-england",
    city: "Gloucester",
    state: "MA",
    lat: 42.6108,
    lng: -70.6592,
    phone: "(978) 283-1812",
    website: null,
    notes: "Inner Harbor commercial / transient docks. Call the harbor master.",
  },
  {
    id: "wentworth-by-the-sea-marina",
    name: "Wentworth by the Sea Marina",
    region: "new-england",
    city: "New Castle",
    state: "NH",
    lat: 43.0586,
    lng: -70.7254,
    phone: "(603) 433-5050",
    website: "https://www.wentworth.com/",
    notes: "Portsmouth Harbor. Resort marina; call.",
  },
  {
    id: "hampton-river-marina",
    name: "Hampton River Marina",
    region: "new-england",
    city: "Hampton",
    state: "NH",
    lat: 42.8948,
    lng: -70.8162,
    phone: "(603) 929-1422",
    website: null,
    notes: "Hampton Harbor. Public listing; call.",
  },
  {
    id: "dimillos-portland",
    name: "DiMillo's Old Port Marina",
    region: "new-england",
    city: "Portland",
    state: "ME",
    lat: 43.6564,
    lng: -70.2502,
    phone: "(207) 773-7251",
    website: "https://www.dimillos.com/",
    notes: "Portland waterfront. Restaurant marina; call for fuel nearby.",
  },
  {
    id: "portland-yacht-services",
    name: "Portland Yacht Services",
    region: "new-england",
    city: "Portland",
    state: "ME",
    lat: 43.6618,
    lng: -70.2486,
    phone: "(207) 774-1067",
    website: "https://www.portlandyacht.com/",
    notes: "East End yard. Fuel and service; no posted pump price.",
  },
  {
    id: "chicks-marina-kennebunkport",
    name: "Chicks Marina",
    region: "new-england",
    city: "Kennebunkport",
    state: "ME",
    lat: 43.3586,
    lng: -70.4768,
    phone: "(207) 967-2782",
    website: "https://www.chicksmarina.com/",
    notes: "Kennebunk River. Classic Maine dock; call.",
  },
  {
    id: "camden-harbor-dock",
    name: "Camden Harbor Park & Amphitheatre Docks",
    region: "new-england",
    city: "Camden",
    state: "ME",
    lat: 44.2096,
    lng: -69.0638,
    phone: "(207) 236-3353",
    website: "https://www.camdenmaine.gov/",
    notes: "Town harbor. Harbor master; call about fuel at adjoining yards.",
  },
  {
    id: "boothbay-harbor-marina",
    name: "Boothbay Harbor Marina",
    region: "new-england",
    city: "Boothbay Harbor",
    state: "ME",
    lat: 43.8524,
    lng: -69.6272,
    phone: "(207) 633-6003",
    website: null,
    notes: "Inner harbor. Public marina listing; call.",
  },
  {
    id: "bar-harbor-town-pier",
    name: "Bar Harbor Town Pier",
    region: "new-england",
    city: "Bar Harbor",
    state: "ME",
    lat: 44.3912,
    lng: -68.2046,
    phone: "(207) 288-5571",
    website: "https://www.barharbormaine.gov/",
    notes: "Municipal pier. Harbor master; call for fuel at the town docks.",
  },
];

function assertUnique(docks: Dock[]) {
  const ids = new Set<string>();
  for (const dock of docks) {
    if (ids.has(dock.id)) throw new Error(`Duplicate dock id ${dock.id}`);
    ids.add(dock.id);
    if (!Number.isFinite(dock.lat) || !Number.isFinite(dock.lng)) {
      throw new Error(`Bad coordinates for ${dock.id}`);
    }
    if (dock.lat < 24 || dock.lat > 48 || dock.lng > -66 || dock.lng < -98) {
      throw new Error(`Coordinates off the US saltwater box for ${dock.id}`);
    }
    const posted = dock.quotes.filter((quote) => quote.status === "posted");
    for (const quote of posted) {
      if (!dock.sourceUrl) {
        throw new Error(`Posted price on ${dock.id} has no sourceUrl`);
      }
    }
  }
}

async function main() {
  const seedPath = path.join(process.cwd(), "data", "docks.seed.json");
  const raw = await readFile(seedPath, "utf8");
  const current = JSON.parse(raw) as {
    generatedAt: string;
    seedCapturedOn: string;
    docks: Array<Dock & { corridor: CorridorId; region?: RegionId }>;
  };

  const homeIds = new Set<string>();
  const home: Dock[] = [];
  for (const dock of current.docks) {
    if (DROP_IDS.has(dock.id)) continue;
    if (dock.corridor !== "galveston-bay" && dock.corridor !== "upper-keys") continue;
    const patched = {
      ...dock,
      region: HOME_REGION[dock.corridor] ?? dock.region ?? "texas",
      ...HOME_PATCHES[dock.id],
    };
    home.push(patched);
    homeIds.add(dock.id);
  }
  for (const extra of HOME_ADDITIONS) {
    if (homeIds.has(extra.id)) continue;
    home.push({ ...extra, ...HOME_PATCHES[extra.id] });
    homeIds.add(extra.id);
  }

  const added = ADDITIONS.filter((row) => !homeIds.has(row.id) && !DROP_IDS.has(row.id)).map(
    toDock,
  );
  const docks = [...home, ...added].filter((dock) => !DROP_IDS.has(dock.id));
  assertUnique(docks);

  const next = {
    generatedAt: "2026-08-30T12:00:00.000Z",
    seedCapturedOn: "2026-08-30",
    docks,
  };

  await writeFile(seedPath, `${JSON.stringify(next, null, 2)}\n`, "utf8");
  const byState = docks.reduce<Record<string, number>>((acc, dock) => {
    acc[dock.state] = (acc[dock.state] ?? 0) + 1;
    return acc;
  }, {});
  console.log(`Wrote ${docks.length} docks (${home.length} home + ${added.length} coast).`);
  console.log(JSON.stringify(byState));
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
